### ISSUE TITLE
Shadow gets apply to all the child components wrapped in a View

### ISSUE THREAD

**Issue by Rakshit17patel** [alan-eu/react-native-fast-shadow#11]
### Describe the bug
On Wrapping a View in ShadowView Component, the shadow gets apply to all the child component of View.

### Expected behavior
The shadow should be only on View Container not on child component

**Comment by simontreny** [comment]
Hi @Rakshit17patel 

Could you please provide a code sample and a screenshot of the bug you encounter?

**Comment by davoam** [comment]
@Rakshit17patel this happens if the view you are applying the shadow does not have a `backgroundColor` property. But if the `backgroundColor` property has value with an alpha channel, RN still applies shadows to children elements on iOS.
