### ISSUE TITLE
SVG support?

### ISSUE THREAD

**Issue by MasonLe2497** [alan-eu/react-native-fast-shadow#12]
Can this library support svg shadow for both android and ios?

**Comment by simontreny** [comment]
Hi @MasonLe2497,

There is no plan to support SVG shadows as they usually rely on gradients, which don't allow to replicate nice looking shadows. Also, the bitmaps used to render these shadows can't be reused between multiple views, so they tend to render slowly and lead to higher memory consumption if used on many views.

The main benefit is that they are compatible out of the box with Expo (as they rely on `react-native-svg` which is supported by Expo). If you can live with the downsides and want Expo compatibility without having to build your own dev client, I encourage you to use [react-native-shadow-2](https://github.com/SrBrahma/react-native-shadow-2) which implements shadows as SVG gradients.
