### ISSUE TITLE
Is it working for expo?

### ISSUE THREAD

**Issue by ggepenyan** [alan-eu/react-native-fast-shadow#6]
This description is a kind request to answer a very important question. Thanks in advance.

**Comment by simontreny** [comment]
Hi @ggepenyan 👋 

This library is not working with Expo [managed workflow](https://docs.expo.dev/introduction/managed-vs-bare/) as it relies on native code that is not available in the Expo Go app.

To use it with Expo, you'll need to switch to the bare workflow and make a custom Expo build for your app. You can find instructions on how to do that [here](https://docs.expo.dev/development/getting-started/).

If you can't do it and still need custom shadows on Android, you're best option is probably to use a library like [react-native-shadow-2](https://github.com/SrBrahma/react-native-shadow-2) that relies on `react-native-svg` (available in Expo managed workflow) to render shadows.

**Comment by younes0** [comment]
@simontreny There is a confusion about wording: expo-dev-client (or developement builds) uses managed workflow. https://docs.expo.dev/develop/development-builds/create-a-build/
So yes, this library is fully compatible with Expo but not Expo Go
